FROM rust:1.81 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM ubuntu:latest
RUN apt update && apt-get install -y ca-certificates
COPY --from=builder /app/target/release/dialer /usr/local/bin
COPY --from=builder /app/checks-dist.toml /etc/dialer.toml
RUN sysctl -w net.ipv4.ping_group_range='0 2147483647'
RUN mkdir -p /var/lib/dialer

ENTRYPOINT ["dialer", "--config", "/etc/dialer.toml"]

